type Query {
  field: Stirng
}

type Image {
  url: String
}

type Page {
  title: String
}

type Paragraph {
  text: DecoratedText
}

type Overview {
  body: String
}

type NumberedStep {
  number: Int
  explanation: String
}

type ImageStep {
  number: Int
  explanation: String
  image: Image
}

type CodeSnippet {
  code: String
}

type CodeSnippetStep {
  number: Int
  explanation: String
  snippet: CodeSnippet
}

type DecoratedText {
  text: String
  boldTextPositions: [Position]
  inlineCodePositions: [Position]
  italicPositions: [Position]
  inlineUrls: [InlineURL]
}

type Position {
  start: Int
  end: Int
}

type InlineURL {
  url: String
  position: Position
}
