type Query {
  page(id: ID): Page
}

type Page {
  title: String
  tasks: [Task]
  isPremium: Boolean
}

type Task {
  name: String
  steps: [Step]
}

type Step {
  number: Int
  description: String
}
"""
interface IStep {
  number: Int
  optional: Boolean
  premium: Boolean
}

type HyperlinkStep implements IStep {
  hyperlink: URL
}

type ScreenShot {
  imageUrl: URL
}

better be a scala type?
"""
type URL {
  string: String
}

type Code {
  _: Boolean
}

type Command {
  _: Boolean
}

type UIoperation {
  _: Boolean
}

type Result {
  _: Boolean
}

type EmbeddedVideo {
  _: Boolean
}

type EmbeddedImage {
  _: Boolean
}
