type Query {
  tutorial(owner: String, name: String)
}

type Tutorial {
  title: String
  pages: [Page]
}

type Page {
  title: String
  elements: [PageElement]
}

union PageElement = Foldable | PlainElement
union PlainElement = Paragraph | Command | Output

type Paragraph {
  body: String
}

type Foldable {
  shortDescription: String
  elements: [PlainElement]
}

type Command {
  command: String
}

type CommandAndOutput {
  command: String
  output: String
}

type DirectoryStructure {
  contents: [String]
}

type Note {
  body: String
}
