type Query {
  relatedInstallations(searchText: String, limit: Int): [Section]
  packageInstallations: [String]
  searchPrerequisites(text: String): [Prerequisite]
}

type Mutation {
  addPage(input: PageCreate): Page
}

type Prerequisite {
  name: String!
  bootstrap: String
  setup: String
}

type Page {
  title: String
}

input PageCreate {
  title: String
}

type Section {
  _: Boolean
}

type SubSection {
  _: Boolean
}
